apiVersion: v1
kind: PersistentVolumeClaim #something we attach to a pod Config not an actual instance of storage
metadata:
  name: database-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
